# Site settings
title: "Harsh Verma"
description: "Master Graduate University of Texas | Software Engineer (Data Science) | Hike | ISRO"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Harsh Verma"
resume_title:                   "Master Graduate University of Texas | Software Engineer (Data Science) | Hike | ISRO"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "harshverma14oct@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "2145162162"
resume_contact_address:         "Texas, USA"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p> Future belongs to those who see possibilities before they become obvious, I Believe in three P's of professional life : passion, persistence and people to learn, grow, solve problems mutually to make things happen.
<br>
Always open to talk about Ideas, Research, Entrepreneurship, Scalable softwares, conference events and Data|Machine learning solutions.<br>
Have an amazing Idea, research, event|conference where you would like to meet and talk; feel free to drop me a message or reach out at-> <b>harshverma14oct@gmail.com</b>
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/iamharshverma"
  resume_twitter_url:           "http://twitter.com/harshverma59"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/harshverma59/"
  resume_instagram_url:         "https://www.instagram.com/intelliovardhan"
  resume_website_url:           "http://harshverma.me"
  resume_medium_url:            "https://medium.com/@harshverma59"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
